### ISSUE TITLE
소개 페이지 섹션 2 리디자인

### ISSUE THREAD

**Issue by Sain-Tech** [dev-oyr/renewal-ourpage#11]
1. 스크롤 '홈커밍' 도달 시 바로 다음 섹션으로 이동할 수 있게 개선 예정
2. 섹션 2 각 설명에 슬라이드 애니메이션 적용 예정
3. 기타 포인트 칼라 및 헤더 - 텍스트 간 마진 변경 사항 적용 예정

**Comment by jun094** [comment]
고생하셨습니당
