### ISSUE TITLE
앞으로 할 일....

### ISSUE THREAD

**Issue by Sain-Tech** [dev-oyr/renewal-ourpage#41]
1. 메인페이지 프로젝트 카드 cascade 애니메이션
2. 프로젝트 더보기 페이지 구현
~~3. 카드 more 역동적으로 애니메이션 개선~~
4. more 버튼 클릭시 항목 없는 것들은 렌더링 안 함
5. 2019 프로젝트 카드 업데이트
6. 프로젝트 데모 이미지 구하기
7. 페이지 전환 시 스크롤 초기화
8. 모집안내 페이지 달력 스크롤 생기는 문제 수정
9. 로그인 후 navbar 구현
10. 게시판 구현

**Comment by eviloliver** [comment]
동민,철진 - 로그인 후 스터디, 공지사항, 마이페이지

**Comment by eviloliver** [comment]
> 동민,철진 - 로그인 후 스터디, 공지사항, 마이페이지
